version: 1
formatters:
  simple:
    format: '%(name)s (%(levelname)s): %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
loggers:
  src.plugins:
    level: INFO
    handlers: [ console ]
    propagate: no
  matplotlib:
    level: INFO
    handlers: [ console ]
    propagate: no
  werkzeug:
    level: ERROR
    handlers: [ console ]
    propagate: no
root:
  level: INFO
  handlers: [console]
disable_existing_loggers: true
