name: docs

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  # Trigger manually
  workflow_dispatch:

  # Trigger on any push to the master
  push:
    branches:
      - main
      - development

  # Trigger on any push to a PR that targets master
  pull_request:
    branches:
      - main
      - development

env:
  name: DeepCAVE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    defaults:
      run:
        shell: bash # Default to using bash on all
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install .
        pip install ".[dev]"

    - name: Make docs
      run: |
        cd docs
        make docs

    - name: Pull latest gh-pages
      if: (contains(github.ref, 'development') || contains(github.ref, 'main'))
      run: |
        cd ..
        git clone https://github.com/automl/${{ env.name }}.git --branch gh-pages --single-branch gh-pages

    - name: Copy new docs into gh-pages
      if: (contains(github.ref, 'development') || contains(github.ref, 'main'))
      run: |
        branch_name=${GITHUB_REF##*/}
        cd ../gh-pages
        rm -rf $branch_name
        cp -r ../${{ env.name }}/docs/build/html $branch_name

    - name: Push to gh-pages
      if: (contains(github.ref, 'development') || contains(github.ref, 'main'))
      run: |
        last_commit=$(git log --pretty=format:"%an: %s")
        cd ../gh-pages
        branch_name=${GITHUB_REF##*/}
        git add $branch_name/
        git config --global user.name 'Github Actions'
        git config --global user.email 'not@mail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "$last_commit"
        git push
