name: Dependency smoke test (Python)

on: 
  # Allow manual trigger of workflow
  workflow_dispatch:

  # Run tests on push/merge to main
  push:
    branches:
      - main
      # TODO: Remove later
      - pytest_update

  # Run tests on anything that has a pull request to main/development
  pull_request:
    branches:
      - main
      - development

jobs:
  smoke:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          python-version: ["3.9", "3.10"] # "3.11" fails due to swig
          os: ["ubuntu-latest"] # "macos-latest", "windows-latest" fails due to swig
    defaults:
      run:
        shell: bash # Default to using bash on all

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install stand alone raytune
        run: |
          pip install swig
          python -m pip install 'deepcave[raytune]'

      - name: Verify raytune dependency is importable
        run: |
          python - <<'PY'
          import importlib
          importlib.import_module(ray.tune)
          PY
